create table tb_car (
   id int8 generated by default as identity,
   championship_standing int4,
   engine varchar(255) not null,
   img_url varchar(255),
   name varchar(255) not null,
   tyre_size int4 not null,
   weight int4 not null,
   year date not null,
   category_id int8,
   primary key (id)
);

create table tb_category (
   id int8 generated by default as identity,
   name varchar(255) not null,
   primary key (id)
);

create table tb_review (
   id int8 generated by default as identity,
   is_rated boolean,
   text varchar(255),
   car_id int8,
   guesser_id int8,
   primary key (id)
);

create table tb_role (
   id int8 generated by default as identity,
   authority varchar(255),
   primary key (id)
);

create table tb_user (
   id int8 generated by default as identity,
   email varchar(255) not null,
   name varchar(255) not null,
   password varchar(255) not null,
   primary key (id)
);

create table tb_user_role (
   user_id int8 not null,
   role_id int8 not null,
   primary key (user_id, role_id)
);

alter table if exists tb_category
   add constraint UK_4gpl7afmaxiecnv7fv7unn2mp unique (name);

alter table if exists tb_user
   add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);

alter table if exists tb_car
   add constraint FKs835v2ur3wt76fm3h63oj03cy
   foreign key (category_id)
   references tb_category;

alter table if exists tb_review
   add constraint FKjkeuuncnhr6qa9juwmnsw4o55
   foreign key (car_id)
   references tb_car;

alter table if exists tb_review
   add constraint FKhg00kn4rssm5tk35yxhqbam5e
   foreign key (guesser_id)
   references tb_user;

alter table if exists tb_user_role
   add constraint FKea2ootw6b6bb0xt3ptl28bymv
   foreign key (role_id)
   references tb_role;

alter table if exists tb_user_role
   add constraint FK7vn3h53d0tqdimm8cp45gc0kl
   foreign key (user_id)
   references tb_user;