version: '3'
services:
  aws-cli-sqs-producer:
    image: mesosphere/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=sa-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10
        aws sqs create-queue --endpoint-url=http://localstack:4566 --queue-name producer-review
      
        sleep 5
        echo Listing queues
        aws sqs --endpoint-url http://localstack:4566 list-queues
      
        while true; do aws sqs --endpoint-url http://localstack:4566 send-message --queue-url http://localhost:4566/000000000000/producer-review --message-body "fast"; sleep 120; done
        sleep 5
      
      "